apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pujp73ufj-python-gitops
  description: This is GitOps manifest for pujp73ufj-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=pujp73ufj-python
    backstage.io/kubernetes-id: pujp73ufj-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: pujp73ufj-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pujp73ufj-python
